export const GET_TASKS = "GET_TASKS";
export const TASK_REQUEST = "TASK_REQUEST"
export const TASK_SUCCESS = "TASK_SUCCESS"
export const TASK_FAILURE = "TASK_FAILURE"
export const TASK_DELETE = "TASK_DELETE"
export const UPDATE_IMPORTANCE = "UPDATE_IMPORTANCE"
export const UPDATE_QUERY = "UPDATE_QUERY"